### ISSUE TITLE
drawio graph generation fails with v0.2.0

### ISSUE THREAD

**Issue by rasanentimo** [srl-labs/clab-io-draw#20]
**Description**

Drawio graph creation fails  because of missing dependency

```
# clab graph --drawio
INFO[0000] Parsing & checking topology file: l3.clab.yml 
INFO[0000] Generating draw.io diagram with version: latest 
ERRO[0000] Command execution failed: exit status 1      
ERRO[0000] Command output: Traceback (most recent call last):
  File "/app/clab2drawio.py", line 5, in <module>
    from lib.Grafana import GrafanaDashboard
  File "/app/lib/Grafana.py", line 4, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel' 
Error: failed to generate diagram: exit status 1
Output: Traceback (most recent call last):
  File "/app/clab2drawio.py", line 5, in <module>
    from lib.Grafana import GrafanaDashboard
  File "/app/lib/Grafana.py", line 4, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

```
# docker run -it -v "$(pwd)":/data ghcr.io/srl-labs/clab-io-draw:latest -i l3.clab.yml 
Traceback (most recent call last):
  File "/app/clab2drawio.py", line 5, in <module>
    from lib.Grafana import GrafanaDashboard
  File "/app/lib/Grafana.py", line 4, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

but it works fine with the previous release

```
# docker run -it -v "$(pwd)":/data ghcr.io/srl-labs/clab-io-draw:v0.1.0 -i l3.clab.yml 
Saved file to: l3.clab.drawio
```

**expected result**

latest version is expected to generate the drawio file.

**proposed fix**

add `ruamel-yaml==0.18.6` to requirements.txt

**Comment by FloSch62** [comment]
What a stupid mistake from me... Thanks @rasanentimo
